name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  pyproject:
    name: runner / pyproject
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      # Checkout this repo and template project for validation testing.
      - uses: actions/checkout@v4
        with: 
          repository: altcoder/template-python
          path: pyproject
          clean: true
      - uses: actions/checkout@v4
        with:
          path: pyaction
          clean: true

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Test the action with python_tool param.
      - name: using python_tool
        uses: ./pyaction
        with:
          root: ./pyproject
          python_tool: pytest

      # Test the action with specific tool as param.
      - name: validation suite
        uses: ./pyaction
        with:
          root: ./pyproject
          black: true
          bandit: true
          pylint: true
          pyright: true
          pytest: true
          pypi_publish: false
          pypi_custom_publish: false          
#          pypi_repo: testpypi
#          pypi_password: ${{ secrets.TEST_PYPI_PASSWORD  }}
#          version_suffix: 'rc${{ github.run_number }}-dev${{ github.run_attempt }}'